---
collections:
  - redhat.rhel_system_roles
  - community.general

  # # CM Workshop
  # - community.vmware
  # - vmware.vmware_rest
  # - awx.awx
  # - containers.podman
  # - devsec.hardening
  # - ansible.posix
  # - fedora.linux_system_roles
  # - epfl_si.rhel
  # - infra.ah_configuration
  # - infra.controller_configuration
  # - redhat_cop.controller_configuration
  # - ansible.windows
  # - chocolatey.chocolatey
  # - community.windows
  # - ansible.windows
  # - dynatrace.oneagent
  # - servicenow.itsm