---
- hosts: all
  name: pingme
  become: yes
  gather_facts: true

  tasks:
    - name: Ping all hosts
      ansible.builtin.ping:
      register: ping_results

    - name: Log ping_results
      ansible.builtin.debug:
        var: ping_results
