---
- name: Control linux services
  hosts: "{{ servername }}"
  become: no
  gather_facts: no

  vars:
  # required
    servicename:
    state:
    # absent, installed, latest, present, removed
    enabled: 
  # defaults
    verbose: false
    wait: false

  tasks:
    - name: Setting service "{{ servicename }}" to state "{{ state }}"
      ansible.builtin.yum:
        name: "{{ servicename }}"
        state: "{{ state }}"
