---
- name: pingme
  hosts: all
  become: false
  gather_facts: true

  vars:
    verbose: false


  tasks:
    - name: Ping host
      ansible.builtin.ping:
      register: ping_results

    - name: Log ping_results
      ansible.builtin.debug:
        var: ping_results
      when: verbose
