---
- name: Register ec2 instance with subscription mangler
  hosts: "{{ _hosts }}"
  become: true
  
  vars:
    _org_id: 6863379
    _activation_key: RHEL9
    _force_register: true

  tasks:
    - name: Check for vars
      ansible.builtin.assert:
        that:
          - org_id is defined
          - activation_key is defined
          - org_id != ''
          - activation_key != ''
          - org_id != 'undef'
          - activation_key != 'undef'

    # - name: Set hostname
    #   ansible.builtin.hostname:
    #     name: "{{ inventory_hostname | regex_replace('_', '-') }}"

    # Install subscription-manager if it's not there
    - name: Install subscription-manager
      ansible.builtin.dnf:
        name: subscription-manager
        state: present

    - name: Register subscription mangler
      redhat_subscription:
        state: present
        activationkey: "{{ _activation_key }}"
        org_id: "{{ _org_id }}"
        force_register: "{{ _force_register }}"
      register: _rhsm_results

    - name: Log _rhsm_results
      ansible.builtin.debug:
        var: _rhsm_results
