---
- hosts: all
  name: ec2_ping
  become: true
  gather_facts: true

  vars:
  # required
    region:
  # defaults
    verbose: false
    wait: false


  tasks:
    - name: Gathering information about "{{ servername }}"
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ servername }}"
      register: ec2_instances

    - name: Log ec2_instances
      ansible.builtin.debug:
        var: ec2_instances
      when: verbose

    - name: Ping host
      ansible.builtin.ping:
      register: ping_results

    - name: Log ping_results
      ansible.builtin.debug:
        var: ping_results
      when: verbose
