---
- name: Control ec2 instance
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  vars:
  # required
    region:
    servername:
  # defaults
    verbose: false

  tasks:
    - name: Gathering information about "{{ servername }}"
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ servername }}"
      register: ec2_instances

    - name: Log ec2_instances
      ansible.builtin.debug:
        var: ec2_instances
      when: verbose


