---
- name: Control AWS instances
  hosts: localhost
  connection: local
  become: no
  gather_facts: no

  vars:
  # required
    region:
    servername:
    state:
  # defaults
    wait: false

  tasks:
    - name: Setting ec2 instance "{{ servername }}" state to "{{ state }}"
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        state: "{{ state }}"
        wait: "{{ wait }}"
        filters:
          "tag:Name": "{{ servername }}"
