---
- hosts: all
  name: ec2_ping
  become: true
  gather_facts: true

  vars:
  # defaults
    verbose: false


  tasks:
    - name: Ping host
      ansible.builtin.ping:
      register: ping_results

    - name: Log ping_results
      ansible.builtin.debug:
        var: ping_results
        # verbosity: 2
      when: verbose
