---
- name: Control AWS instances
  hosts: localhost
  connection: local
  become: no
  gather_facts: no

  # vars:
  #   region:
  #   state:
  #   servername:
  #   vpc_subnet_id:

  tasks:
    - name: Gathering information about "{{ servername }}"
      amazon.aws.ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name": "{{ servername }}"
      register: ec2_node_info

    - name: Setting ec2 "{{ servername }}" state to "{{ state }}"
      amazon.aws.ec2_instance:
        region: "{{ region }}"
        state: "{{ state }}"
        instance_ids: "{{ ec2_node_info.instances[0].instance_id }}"
        # name: "{{ servername }}"
        # vpc_subnet_id: "{{ vpc_subnet_id: }}"
        # tags:
        #   - Name: "{{ servername }}"
