---
- name: rhsm role
  hosts: "{{ _hosts }}"
  become: true
  gather_facts: true

  roles:
      - rhsm_register
        when: _state != 'absent'
      - rhsm_unregister
        when: _state == 'absent'        