---
- name: set_hostname_r
  hosts: "{{ _hosts }}"
  become: true
  gather_facts: false

  pre_tasks:
  - name: Print all available facts
    ansible.builtin.debug:
      var: ansible_facts

  roles:
      - set_hostname